# docker-compose.yml
version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_cicd
    user: root
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
